# input yaml for wgan

arch: 'SNGAN'

path: '/data/medical_images/ISIC-images/'
out: '/medical_imaging/images/fakes/'
run: 'dummy'
seed: 42
n_gpu: 0

num_epochs: 400
learning_rate: 0.0002
beta_adam: 0.5
batch_size: 16

#New parameters of wgan
critic_its: 5
gp_lambda: 10

latent_vector: 256

image_size: 128
loader_workers: 2
number_channels: 3
gen_feature_maps: 64
dis_feature_maps: 64
